export enum Action {
  FIRST_MOVE = 'FIRST_MOVE',
  FIRST_BUILD = 'FIRST_BUILD',
  ENGINEER = 'ENGINEER',
  LOCOMOTIVE = 'LOCOMOTIVE',
  URBANIZATION = 'URBANIZATION',
  PRODUCTION = 'PRODUCTION',
  TURN_ORDER_PASS = 'TURN_ORDER_PASS',
}
